#Linear equations projections etc

###**Import libraries**

In [73]:
import numpy as np
from sympy import Matrix
import pandas as pd
import altair as alt
from scipy.linalg import lu

###**Solving systems of linear equations with Matrices**

Gaussian Elimination

In [7]:
A = np.array([[1, 3, 5],
              [2, 2, -1],
              [1, 3, 2]])
y = np.array([[-1],
              [1],
              [2]])
print("A =",A)
print("y =",y)

A= [[ 1  3  5]
 [ 2  2 -1]
 [ 1  3  2]]
y= [[-1]
 [ 1]
 [ 2]]


In [8]:
np.linalg.solve(A, y)

array([[-2.],
       [ 2.],
       [-1.]])

In [9]:
np.linalg.inv(A)@y

array([[-2.],
       [ 2.],
       [-1.]])

Matrix basis and ranks

In [12]:
A = Matrix([[1, 0, 1],
            [0, 1, 1]])
B = Matrix([[1, 2, 3, -1],
            [2, -1, -4, 8],
            [-1, 1, 3, -5],
            [-1, 2, 5, -6],
            [-1, -2, -3, 1]])
print("A =",A)
print("B =",B)

A = Matrix([[1, 0, 1], [0, 1, 1]])
B = Matrix([[1, 2, 3, -1], [2, -1, -4, 8], [-1, 1, 3, -5], [-1, 2, 5, -6], [-1, -2, -3, 1]])


In [22]:
A_rref, A_pivots = A.rref()
print("RREF A =",A_rref)
print("Pivots of A =",A_pivots)

RREF A = Matrix([[1, 0, 1], [0, 1, 1]])
Pivots of A = (0, 1)


In [23]:
B_rref, B_pivots = B.rref()
print("RREF B =",B_rref)
print("Pivots of B =",B_pivots)

RREF B = Matrix([[1, 0, -1, 0], [0, 1, 2, 0], [0, 0, 0, 1], [0, 0, 0, 0], [0, 0, 0, 0]])
Pivots of B = (0, 1, 3)


###**Matrix norm**

Frobenius norm

In [29]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.linalg.norm(A, 'fro')

16.881943016134134

In [30]:
(np.sum(A**2))**(1/2)

16.881943016134134

Max norm

In [34]:
np.linalg.norm(A, np.inf)

24.0

In [35]:
np.max(np.sum(np.abs(A),axis = 1).tolist())

24

Spectral norm

In [36]:
np.linalg.norm(A, 2)

16.84810335261421

###**Linear and affine mappings**

Example of linear mapping
1. Negation matrix

In [39]:
x = np.array([[-1],
              [0],
              [1]])

y = np.array([[-3],
              [0],
              [2]])

T = np.array([[-1,0,0],
              [0,-1,0],
              [0,0,-1]])
T @ (x+y) == (T @ x) + (T @ y)

array([[ True],
       [ True],
       [ True]])

In [40]:
T @ (x+y)

array([[ 4],
       [ 0],
       [-3]])

In [41]:
alpha = 2
T @ (alpha * x) == alpha * (T @ x)

array([[ True],
       [ True],
       [ True]])

In [42]:
T @ (alpha * x)

array([[ 2],
       [ 0],
       [-2]])

2. Reversal matrix

In [48]:
T = np.array([[0,0,1],
              [0,1,0],
              [1,0,0]])
x_reversal = T @ x
y_reversal = T @ y
print("x: before = \n",x,"\n after = \n",x_reversal)
print("y: before = \n",y,"\n after = \n",y_reversal)

x: before = 
 [[-1]
 [ 0]
 [ 1]] 
 after = 
 [[ 1]
 [ 0]
 [-1]]
y: before = 
 [[-3]
 [ 0]
 [ 2]] 
 after = 
 [[ 2]
 [ 0]
 [-3]]


In [49]:
T @ (x+y) == (T @ x) + (T @ y)

array([[ True],
       [ True],
       [ True]])

In [50]:
T @ (x+y)

array([[ 3],
       [ 0],
       [-4]])

In [51]:
T @ (alpha * x) == alpha * (T @ x)

array([[ True],
       [ True],
       [ True]])

In [52]:
alpha * (T @ x)

array([[ 2],
       [ 0],
       [-2]])

Special linear mapping
1. Scaling

In [53]:
A = np.array([[2.0, 0],
              [0, 2.0]])

x = np.array([[0, 2.0,],
              [0, 4.0,]])
y = A @ x
z = np.column_stack((y,x))
df = pd.DataFrame({'dim-1': z[0], 'dim-2':z[1], 'type': ['tran', 'tran', 'base', 'base']})
df

dim-1  dim-2  type
0    0.0    0.0  tran
1    4.0    8.0  tran
2    0.0    0.0  base
3    2.0    4.0  base

In [54]:
chart = alt.Chart(df).mark_line(opacity=0.8).encode(
    x='dim-1',
    y='dim-2',
    color='type',
    strokeDash='type')

chart

/usr/local/lib/python3.10/dist-packages/altair/utils/core.py:384: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)


alt.Chart(...)

2. Reflection

In [56]:
# rotation along the horiontal axis
A1 = np.array([[1.0, 0],
               [0, -1.0]])

# rotation along the vertical axis
A2 = np.array([[-1.0, 0],
               [0, 1.0]])

# rotation along the line at 45 degrees from the origin
A3 = np.array([[0, 1.0],
               [1.0, 0]])

# rotation along the line at -45 degrees from the origin
A4 = np.array([[0, -1.0],
               [-1.0, 0]])

y1 = A1 @ x
y2 = A2 @ x
y3 = A3 @ x
y4 = A4 @ x
z = np.column_stack((x, y1, y2, y3, y4))
df = pd.DataFrame({'dim-1': z[0], 'dim-2':z[1],
                   'reflection': ['original', 'original',
                                  '0-degrees', '0-degrees',
                                  '90-degrees', '90-degrees',
                                  '45-degrees', '45-degrees',
                                  'neg-45-degrees', 'neg-45-degrees']})
df

dim-1  dim-2      reflection
0    0.0    0.0        original
1    2.0    4.0        original
2    0.0    0.0       0-degrees
3    2.0   -4.0       0-degrees
4    0.0    0.0      90-degrees
5   -2.0    4.0      90-degrees
6    0.0    0.0      45-degrees
7    4.0    2.0      45-degrees
8    0.0    0.0  neg-45-degrees
9   -4.0   -2.0  neg-45-degrees

In [58]:
def base_coor(ran1: float, ran2: float):
    '''return base chart with coordinate space'''
    df_base = pd.DataFrame({'horizontal': np.linspace(ran1, ran2, num=2), 'vertical': np.zeros(2)})

    h = alt.Chart(df_base).mark_line(color='white').encode(
        x='horizontal',
        y='vertical')
    v = alt.Chart(df_base).mark_line(color='white').encode(
        y='horizontal',
        x='vertical')
    base = h + v

    return base

In [59]:
chart = alt.Chart(df).mark_line().encode(
    x=alt.X('dim-1', axis=alt.Axis(title='horizontal-axis')),
    y=alt.Y('dim-2', axis=alt.Axis(title='vertical-axis')),
    color='reflection')

base_coor(-5.0, 5.0) + chart

/usr/local/lib/python3.10/dist-packages/altair/utils/core.py:384: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)


alt.LayerChart(...)

3. Shear

In [60]:
# shear along the horiontal axis
A1 = np.array([[1.0, 1.5],
               [0, 1.0]])
u = np.array([[2, 4.0,],
              [0, 4.0,]])
y1 = A1 @ x
v1 = A1 @ u

z = np.column_stack((x, y1, u, v1))
df = pd.DataFrame({'dim-1': z[0], 'dim-2':z[1],
                   'shear': ['original', 'original',
                             'horizontal', 'horizontal',
                             'original-2', 'original-2',
                             'horizontal-2', 'horizontal-2'
                            ]})
chart = alt.Chart(df).mark_line().encode(
    x=alt.X('dim-1', axis=alt.Axis(title='horizontal-axis')),
    y=alt.Y('dim-2', axis=alt.Axis(title='vertical-axis')),
    color='shear')

base_coor(-5.0, 10.0) + chart

/usr/local/lib/python3.10/dist-packages/altair/utils/core.py:384: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)


alt.LayerChart(...)

4. Rotation

In [61]:
# 90-degrees roration
A1 = np.array([[0, -1.0],
               [1, 0]])

# 180-degrees roration
A2 = np.array([[-1.0, 0],
               [0, -1.0]])

# 270-degrees roration
A3 = np.array([[0, 1.0],
               [-1.0, 0]])

x = np.array([[0, 2.0,],
              [0, 4.0,]])
y1 = A1 @ x
y2 = A2 @ x
y3 = A3 @ x

z = np.column_stack((x, y1, y2, y3))
df = pd.DataFrame({'dim-1': z[0], 'dim-2':z[1],
                   'rotation': ['original', 'original',
                             '90-degrees', '90-degrees',
                             '180-degrees', '180-degrees',
                             '270-degrees', '270-degrees'
                            ]})
df

dim-1  dim-2     rotation
0    0.0    0.0     original
1    2.0    4.0     original
2    0.0    0.0   90-degrees
3   -4.0    2.0   90-degrees
4    0.0    0.0  180-degrees
5   -2.0   -4.0  180-degrees
6    0.0    0.0  270-degrees
7    4.0   -2.0  270-degrees

In [62]:
chart = alt.Chart(df).mark_line().encode(
    x=alt.X('dim-1', axis=alt.Axis(title='horizontal-axis')),
    y=alt.Y('dim-2', axis=alt.Axis(title='vertical-axis')),
    color='rotation')

base_coor(-5.0, 5.0) + chart

/usr/local/lib/python3.10/dist-packages/altair/utils/core.py:384: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)


alt.LayerChart(...)

##**Projections**

Projection onto lines

In [63]:
# base vector
y = np.array([[3],
              [2]])

x = np.array([[1],
              [3]])

P = (y @ y.T)/(y.T @ y)
print(f'Projection matrix for y:\n{P}')

Projection matrix for y:
[[0.69230769 0.46153846]
 [0.46153846 0.30769231]]


In [65]:
z = P @ x
print(f'Projection from x onto y:\n{z}')

Projection from x onto y:
[[2.07692308]
 [1.38461538]]


In [66]:
# origin coordinate space
o = np.array([[0],
              [0]])

v = np.column_stack((o, x, o, y, o, z, x, z))
df = pd.DataFrame({'dim-1': v[0], 'dim-2':v[1],
                   'vector': ['x-vector', 'x-vector',
                              'y-base-vector', 'y-base-vector',
                              'z-projection', 'z-projection',
                              'orthogonal-vector', 'orthogonal-vector'],
                  'size-line': [2, 2, 2, 2, 4, 4, 2, 2]})
df

dim-1     dim-2             vector  size-line
0  0.000000  0.000000           x-vector          2
1  1.000000  3.000000           x-vector          2
2  0.000000  0.000000      y-base-vector          2
3  3.000000  2.000000      y-base-vector          2
4  0.000000  0.000000       z-projection          4
5  2.076923  1.384615       z-projection          4
6  1.000000  3.000000  orthogonal-vector          2
7  2.076923  1.384615  orthogonal-vector          2

In [67]:
chart = alt.Chart(df).mark_line().encode(
    x=alt.X('dim-1', axis=alt.Axis(title='horizontal-axis')),
    y=alt.Y('dim-2', axis=alt.Axis(title='vertical-axis')),
    color='vector',
    strokeDash='vector',
    size = 'size-line')

base_coor(-1.0, 4.0) + chart

/usr/local/lib/python3.10/dist-packages/altair/utils/core.py:384: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)


alt.LayerChart(...)

##**LU Decomposition**

Gaussian elimination

In [68]:
A = np.array([[1, 3, 5],
              [2, 2, -1],
              [1, 3, 2]])

l1 = np.array([[1, 0, 0],
               [-2, 1, 0],
               [0, 0, 1]])
l1 @ A

array([[  1,   3,   5],
       [  0,  -4, -11],
       [  1,   3,   2]])

In [69]:
l2 = np.array([[1, 0, 0],
               [-2, 1, 0],
               [-1, 0, 1]])
l2 @ A

array([[  1,   3,   5],
       [  0,  -4, -11],
       [  0,   0,  -3]])

In [71]:
# inverse of l
L = np.array([[1, 0, 0],
               [2, 1, 0],
               [1, 0, 1]])

# upper triangular resulting from Gaussian Elimination
U = np.array([[1, 3, 5],
              [0, -4, -11],
              [0, 0, -3]])
L @ U

array([[ 1,  3,  5],
       [ 2,  2, -1],
       [ 1,  3,  2]])

Pivoting

In [72]:
P = np.array([[0, 1],
              [1, 0]])
A = np.array([[0, 1],
              [1, 1]])
P @ A

array([[1, 1],
       [0, 1]])

Using SciPy

In [75]:
A = np.array([[2, 1, 1, 0],
              [4, 3, 3, 1],
              [8, 7, 9, 5],
              [6, 7, 9, 8]])
P, L, U = lu(A)
print(f'Pivot matrix:\n{P}')

Pivot matrix:
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [76]:
print(f'Lower triangular matrix:\n{np.round(L, 2)}')

Lower triangular matrix:
[[ 1.    0.    0.    0.  ]
 [ 0.75  1.    0.    0.  ]
 [ 0.5  -0.29  1.    0.  ]
 [ 0.25 -0.43  0.33  1.  ]]


In [77]:
print(f'Upper triangular matrix:\n{np.round(U, 2)}')

Upper triangular matrix:
[[ 8.    7.    9.    5.  ]
 [ 0.    1.75  2.25  4.25]
 [ 0.    0.   -0.86 -0.29]
 [ 0.    0.    0.    0.67]]


In [78]:
A_recover = np.round(P @ L @ U, 1)
print(f'PLU multiplicatin:\n{A_recover.astype(int)}')

PLU multiplicatin:
[[2 1 1 0]
 [4 3 3 1]
 [8 7 9 5]
 [6 7 9 8]]
