#**Determinants and Eigenvalues**

In [1]:
import numpy as np
from sympy import Matrix
import pandas as pd
import altair as alt
from scipy.linalg import lu

###**Determinants**

In [3]:
A = np.array([[4,0],[0,3]])
x = np.array([1,1])
A @ x.T

array([4, 3])

In [4]:
B = np.array([[0.25,0.25],[-0.25,0.25]])
np.linalg.inv(B)

array([[ 2., -2.],
       [ 2.,  2.]])

In [5]:
T = np.array([[2,-2],[2,2]])
T_i = np.linalg.inv(T)
I = np.eye(2)
T_i @ I

array([[ 0.25,  0.25],
       [-0.25,  0.25]])

In [6]:
a = np.array([[-3],[-1]])
T_i @ a

array([[-1. ],
       [ 0.5]])

###**Eigen things**

In [7]:
A = np.array([[4,2],[1,3]])
value,vector = np.linalg.eig(A)
print(value)
print(vector)

[5. 2.]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [8]:
B = np.array([[0,-1],[1,0]])
value,vector = np.linalg.eig(B)
print(value)
print(vector)

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


###**From Deisenroth**

In [9]:
#4.1
A = np.array([[1,3,5],[2,4,6],[0,2,4]])
np.linalg.det(A)

0.0

In [10]:
#4.2
B = np.array([[2,0,1,2,0],[2,-1,0,1,1],[0,1,2,1,2],[-2,0,2,-1,2],[2,0,0,1,1]])
np.linalg.det(B)

6.000000000000003