In [1]:
import numpy as np

##Problem 5

###5.1

In [2]:
A = np.array([[1,2,3],[3,2,1]])
U, S, V_t = np.linalg.svd(A)
print("U=",U)
print("S=",S)
print("V_t=",V_t)

U= [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
S= [4.89897949 2.        ]
V_t= [[-5.77350269e-01 -5.77350269e-01 -5.77350269e-01]
 [ 7.07106781e-01  1.65486686e-16 -7.07106781e-01]
 [ 4.08248290e-01 -8.16496581e-01  4.08248290e-01]]


In [3]:
#Notice that -1 can still be extracted from U and V.t
print("U=",-U)
print("S=",S)
print("V_t=",-V_t)

U= [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
S= [4.89897949 2.        ]
V_t= [[ 5.77350269e-01  5.77350269e-01  5.77350269e-01]
 [-7.07106781e-01 -1.65486686e-16  7.07106781e-01]
 [-4.08248290e-01  8.16496581e-01 -4.08248290e-01]]


In [4]:
S = np.hstack((np.diag(S),np.array([[0],[0]])))
U@S@V_t

array([[1., 2., 3.],
       [3., 2., 1.]])

In [5]:
-U@S@-V_t

array([[1., 2., 3.],
       [3., 2., 1.]])

###5.2

In [6]:
A = np.array([[1,2,3],[3,2,1]])
A_t = np.transpose(A)
Q, R = np.linalg.qr(A_t)
print("Q=",Q)
print("R=",R)

Q= [[-0.26726124  0.87287156]
 [-0.53452248  0.21821789]
 [-0.80178373 -0.43643578]]
R= [[-3.74165739 -2.67261242]
 [ 0.          2.61861468]]


In [7]:
Q@R

array([[1., 3.],
       [2., 2.],
       [3., 1.]])

In [8]:
Q2 = np.array([[np.sqrt(14)/14,(4*np.sqrt(21))/21],[np.sqrt(14)/7,np.sqrt(21)/21],[(3*np.sqrt(14))/14,(-2*np.sqrt(21))/21]])
R2 = np.array([[np.sqrt(14),(5*np.sqrt(14))/7],[0,(4*np.sqrt(21))/7]])
Q2@R2

array([[1., 3.],
       [2., 2.],
       [3., 1.]])

In [9]:
print("Q2=",Q2)
print("Q=",Q)
print("R2=",R2)
print("R=",R)

Q2= [[ 0.26726124  0.87287156]
 [ 0.53452248  0.21821789]
 [ 0.80178373 -0.43643578]]
Q= [[-0.26726124  0.87287156]
 [-0.53452248  0.21821789]
 [-0.80178373 -0.43643578]]
R2= [[3.74165739 2.67261242]
 [0.         2.61861468]]
R= [[-3.74165739 -2.67261242]
 [ 0.          2.61861468]]


In [10]:
#Notice that in the Python algorithm, the first orthonomal vector is scaled with -1. Starting with an unscaled orthonormal vector would result to
Q[:,0] = Q[:,0]*-1
print(Q)

[[ 0.26726124  0.87287156]
 [ 0.53452248  0.21821789]
 [ 0.80178373 -0.43643578]]


In [11]:
R = np.transpose(Q)@A_t
print(R)

[[3.74165739e+00 2.67261242e+00]
 [6.66133815e-16 2.61861468e+00]]


In [12]:
Q@R

array([[1., 3.],
       [2., 2.],
       [3., 1.]])

##Problem 6

###6.1

In [13]:
A = np.array([[1,2,3],[3,2,1]])
A_t = np.transpose(A)
AA_t = A@A_t
np.linalg.eig(AA_t)

EigResult(eigenvalues=array([24.,  4.]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))

In [14]:
X = np.array([[1,1],[1,-1]])
X_in = np.linalg.inv(X)
Eig_mat = np.array([[24,0],[0,4]])
Ans = X@Eig_mat@X_in
print(Ans)

[[14. 10.]
 [10. 14.]]


In [15]:
np.linalg.eig

<function eig at 0x7b9ced3f26f0>

###6.2

In [16]:
A = np.array([[1,2,3],[3,2,1]])
A_t = np.transpose(A)
AA_t = A@A_t
AA_t_in = np.linalg.inv(AA_t)
b = np.array([1,1,1])
x = AA_t_in@A@b
print(x)

[0.25 0.25]
