#**Eigendecomposition**

In [24]:
import numpy as np
from sympy import Matrix
import pandas as pd
import altair as alt
from scipy.linalg import lu

###**Eigendecomposition**

In [25]:
A = np.array([[5,  3, 0],
              [2,  6, 0],
              [4,  -2, 2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[2. 8. 3.]

Eigenvectors:
[[ 0.          0.6882472   0.18291323]
 [ 0.          0.6882472  -0.12194215]
 [ 1.          0.22941573  0.97553722]]


In [26]:
X = eigenvectors
I = np.identity(3)
L = I * eigenvalues
print(f'AX = \n{A@X}')
print(f'XL = \n{X@L}')

AX = 
[[ 0.          5.50597761  0.54873968]
 [ 0.          5.50597761 -0.36582646]
 [ 2.          1.83532587  2.92661165]]
XL = 
[[ 0.          5.50597761  0.54873968]
 [ 0.          5.50597761 -0.36582646]
 [ 2.          1.83532587  2.92661165]]


In [27]:
print(f'Entry-wise comparison: {np.allclose(A @ X, X @ L)}')

Entry-wise comparison: True


In [28]:
A@X == X@L

array([[ True,  True, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [29]:
X_inv = np.linalg.inv(X)
print(f'A = \n{A}\n')
print(f'XAX_inv = \n{X @ L @ X_inv}')

A = 
[[ 5  3  0]
 [ 2  6  0]
 [ 4 -2  2]]

XAX_inv = 
[[ 5.  3.  0.]
 [ 2.  6.  0.]
 [ 4. -2.  2.]]


###**Singular Value Decomposition**

In [30]:
# 2 x 3 matrix
A_wide = np.array([[2, 1, 0],
                   [-3, 0, 1]])

# 3 x 2 matrix
A_tall = np.array([[2, 1],
                   [-3, 0],
                   [0, 2]])

# 3 x 3 matrix: col 3 equals 2 x col 1
A_square = np.array([[2, 1, 4],
                     [-3, 0, -6],
                     [1, 2, 2]])

U1, S1, V_T1 = np.linalg.svd(A_wide)
U2, S2, V_T2 = np.linalg.svd(A_tall)
U3, S3, V_T3 = np.linalg.svd(A_square)

print(f'Left orthogonal matrix wide A:\n{np.round(U1, 2)}\n')
print(f'Singular values diagonal matrix wide A:\n{np.round(S1, 2)}\n')
print(f'Right orthogonal matrix wide A:\n{np.round(V_T1, 2)}')

Left orthogonal matrix wide A:
[[-0.55  0.83]
 [ 0.83  0.55]]

Singular values diagonal matrix wide A:
[3.74 1.  ]

Right orthogonal matrix wide A:
[[-0.96 -0.15  0.22]
 [-0.    0.83  0.55]
 [ 0.27 -0.53  0.8 ]]


In [31]:
print(f'Left orthogonal matrix for tall A:\n{np.round(U2, 2)}\n')
print(f'Singular values diagonal matrix for tall A:\n{np.round(S2, 2)}\n')
print(f'Right orthogonal matrix for tall A:\n{np.round(V_T2, 2)}')

Left orthogonal matrix for tall A:
[[-0.59 -0.24 -0.77]
 [ 0.8  -0.32 -0.51]
 [-0.13 -0.91  0.38]]

Singular values diagonal matrix for tall A:
[3.67 2.13]

Right orthogonal matrix for tall A:
[[-0.97 -0.23]
 [ 0.23 -0.97]]


In [32]:
print(f'Left orthogonal matrix for square A:\n{np.round(U3, 2)}\n')
print(f'Singular values diagonal matrix for square A:\n{np.round(S3, 2)}\n')
print(f'Right orthogonal matrix for square A:\n{np.round(V_T3, 2)}')

Left orthogonal matrix for square A:
[[-0.54 -0.2  -0.82]
 [ 0.79 -0.46 -0.41]
 [-0.29 -0.86  0.41]]

Singular values diagonal matrix for square A:
[8.44 1.95 0.  ]

Right orthogonal matrix for square A:
[[-0.44 -0.13 -0.89]
 [ 0.06 -0.99  0.12]
 [ 0.89  0.   -0.45]]


In [33]:
Z = np.array([[1, 2, 3],
             [3, 6, 9],
             [4, 8, 12],
             [5, 10, 15]])
U4, S4, V_T4 = np.linalg.svd(Z)
print(f'Left orthogonal matrix for square A:\n{np.round(U4, 2)}\n')
print(f'Singular values diagonal matrix for square A:\n{np.round(S4, 2)}\n')
print(f'Right orthogonal matrix for square A:\n{np.round(V_T4, 2)}')

Left orthogonal matrix for square A:
[[-0.14 -0.56 -0.42 -0.7 ]
 [-0.42 -0.21  0.85 -0.26]
 [-0.56  0.72 -0.21 -0.34]
 [-0.7  -0.34 -0.26  0.57]]

Singular values diagonal matrix for square A:
[26.72  0.    0.  ]

Right orthogonal matrix for square A:
[[-0.27 -0.53 -0.8 ]
 [ 0.   -0.83  0.55]
 [ 0.96 -0.15 -0.22]]


###**From Deisenroth**

In [34]:
#4.7
A1 = np.array([[0,1],
               [-8,4]])
eigenval, eigenvec = np.linalg.eig(A1)
P_inv = np.linalg.inv(eigenvec)
print(P_inv)

[[-1.24900090e-16+2.12132034j  5.30330086e-01-0.53033009j]
 [ 1.24900090e-16-2.12132034j  5.30330086e-01+0.53033009j]]


In [35]:
#4.7
A2 = np.array([[1,1,1],
               [1,1,1],
               [1,1,1]])
eigenval, eigenvec = np.linalg.eig(A2)
P_inv = np.linalg.inv(eigenvec)
print(P_inv)

[[-8.16496581e-01  4.08248290e-01  4.08248290e-01]
 [ 5.77350269e-01  5.77350269e-01  5.77350269e-01]
 [-3.92523115e-17 -7.07106781e-01  7.07106781e-01]]


In [39]:
#4.7
A3 = np.array([[5,4,2,1],
               [0,1,-1,-1],
               [-1,-1,3,0],
               [1,1,-1,2]])
eigenval, eigenvec = np.linalg.eig(A3)
P_inv = np.linalg.inv(eigenvec)
print(P_inv)

[[-1.80143985e+15 -1.80143985e+15 -1.80143985e+15 -1.40000000e+00]
 [-1.80143985e+15 -1.80143985e+15 -1.80143985e+15 -1.40000000e+00]
 [ 0.00000000e+00  1.41421356e+00  1.41421356e+00  1.41421356e+00]
 [-0.00000000e+00  1.29808447e-15 -1.73205081e+00 -1.73205081e+00]]


In [59]:
#4.8
U = np.array([[1/(2**(1/2)),-1/(2**(1/2))],[1/(2**(1/2)),1/(2**(1/2))]])
Sigma = np.array([[5,0,0],[0,3,0]])
V_T = np.array([[1/(2**(1/2)),1/(2)**(1/2),0],[-1/(3*(2)**(1/2)),1/(3*(2**(1/2))),-2/3],[-2/3,2/3,1/3]])
A = U@Sigma@V_T
print(A)

[[ 3.          2.          1.41421356]
 [ 2.          3.         -1.41421356]]


In [56]:
#4.9
U = np.array([[1,0],[0,1]])
Sigma = np.array([[2*(2**(1/2)),0],[0,2**(1/2)]])
V_T = np.array([[1/(2)**(1/2),1/(2)**(1/2)],[-1/(2)**(1/2),1/(2)**(1/2)]])
A = U@Sigma@V_T
print(A)

[[ 2.  2.]
 [-1.  1.]]
