#**Vectors and Matrices**

###**Import libraries**

In [1]:
import numpy as np
import pandas as pd
import altair as alt

###**Vectors**

Generate vector

In [3]:
x = np.array([[1],[2],[3]])
x.shape

(3, 1)

In [4]:
print(f'A 3-dimensional vector:\n{x}')

A 3-dimensional vector:
[[1]
 [2]
 [3]]


Adding vectors

In [5]:
y = x
x + y

array([[2],
       [4],
       [6]])

In [6]:
np.add(x,y)

array([[2],
       [4],
       [6]])

Scalar multiplication

In [7]:
a = 2
a * x

array([[2],
       [4],
       [6]])

Linear combination

In [8]:
b = 3
a*x + b*y

array([[ 5],
       [10],
       [15]])

Dot product

In [9]:
x.T @ y

array([[14]])

Euclidian norm

In [11]:
np.linalg.norm(x,2)

3.7416573867739413

Manhattan norm

In [12]:
np.linalg.norm(x,1)

6.0

Max norm

In [13]:
np.linalg.norm(x,np.inf)

3.0

Distance

In [15]:
distance = np.linalg.norm(x-2*y, 2)
print(f'L_2 distance : {distance}')

L_2 distance : 3.7416573867739413


Cosine

In [16]:
z  = np.array([[1],[1],[1]])
cos_theta = (x.T @ z) / (np.linalg.norm(x,2) * np.linalg.norm(z,2))
print(f'cos of the angle = {np.round(cos_theta, 3)}')

cos of the angle = [[0.926]]


In [17]:
cos_inverse = np.arccos(cos_theta)
print(f'angle in radiants = {np.round(cos_inverse, 3)}')

angle in radiants = [[0.388]]


In [18]:
degrees = cos_inverse * ((180)/np.pi)
print(f'angle in degrees = {np.round(degrees, 3)}')

angle in degrees = [[22.208]]


Orthogonal vectors

In [19]:
w = np.array([[1], [0]])
v = np.array([[0], [1]])

cos_theta = (w.T @ v) / (np.linalg.norm(w,2) * np.linalg.norm(v,2))
print(f'cos of the angle = {np.round(cos_theta, 3)}')

cos of the angle = [[0.]]


In [20]:
cos_inverse = np.arccos(cos_theta)
degrees = cos_inverse * ((180)/np.pi)
print(f'angle in radiants = {np.round(cos_inverse, 3)}\nangle in degrees ={np.round(degrees, 3)} ')

angle in radiants = [[1.571]]
angle in degrees =[[90.]] 


System of linear equations

In [21]:
df = pd.DataFrame({"x1": [0, 2], "y1":[8, 3], "x2": [0.5, 2], "y2": [0, 3]})
equation1 = alt.Chart(df).mark_line().encode(x="x1", y="y1")
equation2 = alt.Chart(df).mark_line(color="red").encode(x="x2", y="y2")
equation1 + equation2

alt.LayerChart(...)

###**Matrices**

Create a matrix

In [32]:
A = np.array([[0,2,1],  # 1st row
              [1,4,1], # 2nd row
             [5,6,1]]) # 3rd row

print(f'a 3x3 Matrix:\n{A}')

a 3x3 Matrix:
[[0 2 1]
 [1 4 1]
 [5 6 1]]


Matrix addition

In [33]:
B = np.array([[3,1,0],
              [-3,2,1],
              [1,2,3]])
A + B

array([[ 3,  3,  1],
       [-2,  6,  2],
       [ 6,  8,  4]])

In [34]:
np.add(A, B)

array([[ 3,  3,  1],
       [-2,  6,  2],
       [ 6,  8,  4]])

Scalar multiplication

In [35]:
a * A

array([[ 0,  4,  2],
       [ 2,  8,  2],
       [10, 12,  2]])

In [36]:
np.multiply(a,A)

array([[ 0,  4,  2],
       [ 2,  8,  2],
       [10, 12,  2]])

Matrix-vector multiplication

In [37]:
A @ x

array([[ 7],
       [12],
       [20]])

In [38]:
np.dot(A,x)

array([[ 7],
       [12],
       [20]])

Matrix-matrix multiplication

In [39]:
A @ B

array([[-5,  6,  5],
       [-8, 11,  7],
       [-2, 19,  9]])

In [40]:
np.dot(A,B)

array([[-5,  6,  5],
       [-8, 11,  7],
       [-2, 19,  9]])

Matrix inverse

In [41]:
A_i = np.linalg.inv(A)
print(f'A inverse:\n{A_i}')

A inverse:
[[ 0.33333333 -0.66666667  0.33333333]
 [-0.66666667  0.83333333 -0.16666667]
 [ 2.33333333 -1.66666667  0.33333333]]


In [42]:
I = np.round(A_i @ A)
print(f'A_i times A resulsts in I_3:\n{I}')

A_i times A resulsts in I_3:
[[ 1. -0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Matrix transpose

In [43]:
A.T

array([[0, 1, 5],
       [2, 4, 6],
       [1, 1, 1]])

Hadamard product

In [44]:
A * B

array([[ 0,  2,  0],
       [-3,  8,  1],
       [ 5, 12,  3]])

In [45]:
np.multiply(A,B)

array([[ 0,  2,  0],
       [-3,  8,  1],
       [ 5, 12,  3]])